-- Oracle-source corpus (swept: oracle -> {tsql, postgresql, mysql}).
-- Oracle idioms (FROM dual, SYSDATE, ROWNUM, sequences) that must be translated.
-- @@@
SELECT 1 FROM dual
-- @@@
SELECT SYSDATE FROM dual
-- @@@
SELECT SYSTIMESTAMP FROM dual
-- @@@
SELECT NVL(NULL, 1) AS c FROM dual
-- @@@
SELECT NVL2(1, 'a', 'b') AS c FROM dual
-- @@@
SELECT SUBSTR('hello', 1, 3) AS s FROM dual
-- @@@
SELECT INSTR('hello', 'l') AS p FROM dual
-- @@@
SELECT 'a' || 'b' || 'c' AS concatenated FROM dual
-- @@@
SELECT LENGTH('hello') AS l FROM dual
-- @@@
SELECT DECODE(1, 1, 'one', 2, 'two', 'other') AS d FROM dual
-- @@@
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') AS d FROM dual
-- @@@
SELECT TO_DATE('2024-01-01', 'YYYY-MM-DD') AS d FROM dual
-- @@@
SELECT x FROM (SELECT 1 AS x UNION SELECT 2) t WHERE ROWNUM <= 1
-- @@@
SELECT MOD(10, 3) AS m, TRUNC(3.7) AS t FROM dual
-- @@@
CREATE TABLE corpus_ora_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(100) NOT NULL,
    price NUMBER(10, 2) DEFAULT 0,
    notes CLOB NULL,
    payload BLOB NULL,
    created TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT pk_corpus_ora PRIMARY KEY (id)
)
-- @@@
CREATE TABLE corpus_ora_dml (id NUMBER PRIMARY KEY, n NUMBER);
INSERT INTO corpus_ora_dml (id, n) VALUES (1, 10);
UPDATE corpus_ora_dml SET n = n + 1 WHERE id = 1;
