# Copyright (c) 2026 Jesús Diéguez Fernández
# SPDX-License-Identifier: MIT
# See the LICENSE file in the project root for full license text.

"""RC-3 — clause drops (data-integrity constraints must not vanish silently).

Inline column-level constraints (``c INT REFERENCES p(id) ON DELETE CASCADE``,
``c INT CHECK (c > 0)``) used to be dropped by the CREATE TABLE converter — it
read only NOT NULL / IDENTITY / PRIMARY KEY / UNIQUE / DEFAULT. They are
equivalent to a table-level constraint and are now routed there, so the
referential-integrity / validation rule survives on every target.
"""

from __future__ import annotations

import sqlglot

from unique.core.transpiler import Transpiler

_SG = {"mysql": "mysql", "tsql": "tsql", "oracle": "oracle", "postgresql": "postgres"}


def _t(sql: str, source: str, target: str) -> str:
    return Transpiler().transpile(sql, source, target).sql


def _parses(sql: str, target: str) -> bool:
    try:
        sqlglot.parse(sql, read=_SG[target], error_level=sqlglot.ErrorLevel.RAISE)
        return True
    except Exception:
        return False


def test_inline_fk_with_on_delete_survives_to_every_target() -> None:
    src = "CREATE TABLE t (a INT, b INT REFERENCES p(id) ON DELETE CASCADE)"
    for tgt in ("mysql", "tsql", "oracle"):
        out = _t(src, "postgresql", tgt)
        assert "REFERENCES" in out.upper(), (tgt, out)  # FK not dropped
        assert "ON DELETE CASCADE" in out.upper(), (tgt, out)  # action kept
        assert _parses(out, tgt), (tgt, out)


def test_inline_check_survives() -> None:
    for src_dialect in ("postgresql", "mysql"):
        out = _t("CREATE TABLE t (a INT CHECK (a > 0))", src_dialect, "tsql")
        assert "CHECK (a > 0)" in out, (src_dialect, out)
        assert _parses(out, "tsql"), (src_dialect, out)


def test_inline_fk_without_action_survives() -> None:
    out = _t("CREATE TABLE t (b INT REFERENCES p(id))", "mysql", "postgresql")
    assert "REFERENCES" in out.upper(), out
    assert _parses(out, "postgresql"), out


def test_identity_seed_and_step_preserved() -> None:
    # IDENTITY(100, 5) seed/step must survive (live-verified: pg yields 100, 105).
    src = "CREATE TABLE t (a INT IDENTITY(100, 5))"
    pg = _t(src, "tsql", "postgresql")
    assert "START WITH 100 INCREMENT BY 5" in pg, pg
    assert _parses(pg, "postgresql")
    orc = _t(src, "tsql", "oracle")
    assert "START WITH 100 INCREMENT BY 5" in orc, orc
    # Round-trip pg GENERATED … START WITH → tsql IDENTITY(seed, step).
    back = _t(
        "CREATE TABLE t (a INT GENERATED BY DEFAULT AS IDENTITY "
        "(START WITH 50 INCREMENT BY 2))",
        "postgresql",
        "tsql",
    )
    assert "IDENTITY(50,2)" in back, back


def test_identity_default_still_serial() -> None:
    # The (1, 1) default keeps the idiomatic SERIAL on PostgreSQL.
    out = _t("CREATE TABLE t (a INT IDENTITY(1, 1))", "tsql", "postgresql")
    assert "SERIAL" in out and "START WITH" not in out, out


def test_column_comment_preserved() -> None:
    src = "CREATE TABLE t (a INT COMMENT 'the id')"
    assert "COMMENT ON COLUMN t.a IS 'the id'" in _t(src, "mysql", "postgresql")
    assert "COMMENT ON COLUMN t.a IS 'the id'" in _t(src, "mysql", "oracle")
    assert "COMMENT 'the id'" in _t(src, "mysql", "mysql")
    tsql = _t(src, "mysql", "tsql")
    assert (
        "the id" in tsql and "-- UNIQUE:" not in tsql
    ), tsql  # plain note, not a carrier


def test_oracle_fk_on_update_stripped() -> None:
    # Oracle has no ON UPDATE referential action; keep the FK + ON DELETE, drop
    # ON UPDATE (rather than ship invalid DDL). Documented limitation.
    out = _t(
        "CREATE TABLE t (a INT, b INT, CONSTRAINT fk FOREIGN KEY (b) "
        "REFERENCES p(id) ON DELETE CASCADE ON UPDATE CASCADE)",
        "postgresql",
        "oracle",
    )
    assert "ON UPDATE" not in out.upper(), out
    assert "ON DELETE CASCADE" in out.upper(), out
    assert _parses(out, "oracle"), out


def test_identity_generated_always_vs_by_default_preserved() -> None:
    always = _t(
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY)", "postgresql", "oracle"
    )
    assert "GENERATED ALWAYS AS IDENTITY" in always, always
    bydef = _t(
        "CREATE TABLE t (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 5))",
        "postgresql",
        "oracle",
    )
    assert "GENERATED BY DEFAULT AS IDENTITY" in bydef, bydef
