# Copyright (c) 2026 Jesús Diéguez Fernández
# SPDX-License-Identifier: MIT
# See the LICENSE file in the project root for full license text.

"""Unit tests for scripts/generate_reference_docs.py (docs/TODO.md T8)."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

_PATH = Path(__file__).resolve().parents[2] / "scripts" / "generate_reference_docs.py"
_spec = importlib.util.spec_from_file_location("generate_reference_docs", _PATH)
assert _spec is not None and _spec.loader is not None
gen = importlib.util.module_from_spec(_spec)
# dataclass() resolves string-form annotations (PEP 563) via
# sys.modules[cls.__module__] -- register before exec_module so it can find
# this module's own namespace (mirrors tests/unit/test_challenge_stats.py).
sys.modules["generate_reference_docs"] = gen
_spec.loader.exec_module(gen)


class TestDeterminism:
    def test_two_runs_produce_identical_pages(self) -> None:
        first = gen.generate_all()
        second = gen.generate_all()
        assert first == second
        assert first is not second

    def test_page_set_is_the_expected_twelve_pairs_plus_two(self) -> None:
        pages = gen.generate_all()
        expected_pairs = {
            f"mappings-{s}-{t}.md"
            for s in gen.mappings.DIALECTS
            for t in gen.mappings.DIALECTS
            if s != t
        }
        assert len(expected_pairs) == 12
        assert expected_pairs <= set(pages)
        assert {"limits.md", "coverage.md"} <= set(pages)
        assert len(pages) == 14

    def test_every_page_carries_the_generated_banner(self) -> None:
        pages = gen.generate_all()
        for name, content in pages.items():
            assert "Generated — do not edit by hand" in content, name
            assert "generate_reference_docs.py" in content, name


class TestCheckGate:
    def test_check_passes_on_freshly_written_output(self, tmp_path: Path) -> None:
        pages = gen.generate_all()
        gen.write_pages(pages, tmp_path)
        assert gen.check(tmp_path) == 0

    def test_check_fails_on_a_mutated_file(self, tmp_path: Path) -> None:
        pages = gen.generate_all()
        gen.write_pages(pages, tmp_path)
        (tmp_path / "coverage.md").write_text("mutated content\n", encoding="utf-8")
        assert gen.check(tmp_path) == 1

    def test_check_fails_when_a_generated_file_is_missing(self, tmp_path: Path) -> None:
        pages = gen.generate_all()
        gen.write_pages(pages, tmp_path)
        (tmp_path / "coverage.md").unlink()
        assert gen.check(tmp_path) == 1

    def test_check_fails_on_an_orphaned_extra_file(self, tmp_path: Path) -> None:
        pages = gen.generate_all()
        gen.write_pages(pages, tmp_path)
        (tmp_path / "orphan.md").write_text("not generated by us\n", encoding="utf-8")
        assert gen.check(tmp_path) == 1

    def test_main_check_flag_wires_to_check(self, tmp_path: Path) -> None:
        pages = gen.generate_all()
        gen.write_pages(pages, tmp_path)
        assert gen.main(["--check", "--out-dir", str(tmp_path)]) == 0
        (tmp_path / "coverage.md").write_text("mutated\n", encoding="utf-8")
        assert gen.main(["--check", "--out-dir", str(tmp_path)]) == 1


class TestLimitCatalogParser:
    def test_parses_id_class_description_and_citation(self) -> None:
        text = (
            "-- CASE[limit][class=invalid]: my-case-id — a short description "
            "that cites (docs/03-unsupported.md §3.1) for the reason. fails on oracle\n"
            "SELECT 1;\n"
        )
        rows = gen.parse_limit_catalog(text, source="mysql")
        assert len(rows) == 1
        row = rows[0]
        assert row.case_id == "my-case-id"
        assert row.source == "mysql"
        assert row.klass == "invalid"
        assert row.citation == "docs/03-unsupported.md §3.1"
        assert "short description" in row.description
        assert row.code == ""

    def test_untagged_class_defaults_to_unclassified(self) -> None:
        text = "-- CASE[limit]: some-id — no class tag here (docs/03-unsupported.md)\n"
        rows = gen.parse_limit_catalog(text, source="oracle")
        assert len(rows) == 1
        assert rows[0].klass == gen.cs_unclassified()

    def test_citation_without_section_number(self) -> None:
        text = (
            "-- CASE[limit]: bare-cite — degrades with no section "
            "(docs/03-unsupported.md)\n"
        )
        rows = gen.parse_limit_catalog(text, source="postgresql")
        assert rows[0].citation == "docs/03-unsupported.md"

    def test_description_without_recognizable_id_prefix_stays_untitled(self) -> None:
        text = "-- CASE[limit]: this has no em-dash separator at all\n"
        rows = gen.parse_limit_catalog(text, source="tsql")
        assert len(rows) == 1
        assert rows[0].case_id == ""
        assert "no em-dash separator" in rows[0].description

    def test_only_limit_status_cases_are_returned(self) -> None:
        text = (
            "-- CASE[fixed][class=func]: fixed-case — ignored\n"
            "-- CASE[open][class=crash]: open-case — ignored too\n"
            "-- CASE[limit]: limit-case — this one — kept (docs/03-unsupported.md)\n"
        )
        rows = gen.parse_limit_catalog(text, source="mysql")
        assert len(rows) == 1
        assert rows[0].case_id == "limit-case"

    def test_non_case_lines_are_ignored(self) -> None:
        text = "SELECT 1;\n-- just a regular comment\n"
        assert gen.parse_limit_catalog(text, source="mysql") == []

    def test_mixed_case_id_is_recognized(self) -> None:
        text = (
            "-- CASE[limit]: my-drop4-ZEROFILL — a mixed-case id "
            "(docs/03-unsupported.md §3.22)\n"
        )
        rows = gen.parse_limit_catalog(text, source="mysql")
        assert rows[0].case_id == "my-drop4-ZEROFILL"

    def test_build_limits_catalog_matches_real_corpus_limit_count(self) -> None:
        cs = gen._load_challenge_stats()  # noqa: SLF001
        headers = cs.parse_corpus(gen._CHALLENGE_DIR)  # noqa: SLF001
        expected = sum(1 for h in headers if h.status == "limit")
        rows = gen.build_limits_catalog()
        assert len(rows) == expected
        # every row's source is one of the corpus's own dialect stems
        assert {r.source for r in rows} <= {h.source for h in headers}


class TestRenderLimitsPage:
    def test_renders_a_row_per_case_with_citation_link(self) -> None:
        rows = [
            gen.LimitRow(
                case_id="x-case",
                source="mysql",
                klass="func",
                description="a description",
                citation="docs/03-unsupported.md §3.1",
            )
        ]
        page = gen.render_limits_page(rows)
        assert "`x-case`" in page
        assert "mysql" in page
        assert "`func`" in page
        assert "a description" in page
        assert "[03-unsupported.md §3.1](../03-unsupported.md)" in page
        assert "1 `[limit]` cases across 1 source engine(s)." in page


class TestRenderCoveragePage:
    def test_reflects_real_corpus_counts(self) -> None:
        page = gen.render_coverage_page()
        cs = gen._load_challenge_stats()  # noqa: SLF001
        headers = cs.parse_corpus(gen._CHALLENGE_DIR)  # noqa: SLF001
        assert "| **all** |" in page
        assert str(len(headers)) in page
